# Generated by Django 5.2.4 on 2025-07-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
