# Generated by Django 5.2.4 on 2025-07-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0003_product_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product")),
            ],
        ),
    ]
