# Generated by Django 5.2.4 on 2025-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.TextField(),
        ),
    ]
