# Generated by Django 5.2.4 on 2025-07-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0005_profile_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="static/images/3d_default.jpg", upload_to="product"
            ),
        ),
    ]
