# Generated by Django 5.2.4 on 2025-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="product/3d_default.jpg", upload_to="product"
            ),
        ),
    ]
