# Generated by Django 5.2.4 on 2025-07-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="us",
            new_name="user",
        ),
    ]
