# Generated by Django 5.2.4 on 2025-07-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eapp", "0009_rename_us_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="ProfileImg/3d_default.jpg", upload_to="product"
            ),
        ),
    ]
